site_name: Physics 2024/25 Summer
nav:
  - ğŸ  Home: index.md
  - âš™ï¸ Mechanics:
    - ğŸ“ Lecture Notes:
      - Language of Physics: Mechanics/Language_of_physics.html
      - Mechanics: Mechanics/Mechanics.html
      - Waves: Mechanics/Waves.html
    - Student Projects:
      - Logistic Equation: Mechanics/sp/logistic_equation_bifurcation.md
      - Double Pendulum: Mechanics/sp/double_pendulum_trajectories.md
      - Lorenz Attractor: Mechanics/sp/lorenz_system_and_attractor.md
      - Predator-Prey Model: Mechanics/sp/predator_prey_model.md
      - Duffing Oscillator: Mechanics/sp/duffing_oscillator.md
      - Henon Map: Mechanics/sp/henon_map.md
      - Chua's Circuit: Mechanics/sp/chuas_circuit.md
      - Pendulum with Damping: Mechanics/sp/pendulum_with_damping_and_forcing.md
      - Three Body Problem: Mechanics/sp/three_body_problem.md
  - âš¡ Electromagnetism:
    - ğŸ“ Lecture Notes:
      - Electromagnetism: Electromagnetism/Electromagnetism.html
      - Circuits: Electromagnetism/Circuits.html
    - Student Projects:
      - Kirchhoff Laws: Electromagnetism/sp/Kirchhoff_laws.md
      - Aurora Borealis: Electromagnetism/sp/solar_wind.md
  - ğŸ”¬ Experiments:
    - ğŸ“ Lecture Notes:
      - Statistics 101: Experiments_Statistics/Statistics.html
      - Measurements: Experiments_Statistics/Measurement.html
    - Student Projects:
      - Estiamting Pi: Experiments_Statistics/sp/estimation_of_pi.md
  - âš›ï¸ Modern Physics:
    - ğŸ“ Lecture Notes:
      - Quantum Mechanics: Modern_Physics/Quantum_mechanics.html
      - Cosmology: Modern_Physics/Cosmology.html
    - Student Projects:
      - Quantum Harmonic Oscillator: Modern_Physics/sp/quantum_harmonic_oscillator.md
  - âœï¸ Exercises for Students:
    - Problem list: Exercises_for_Students/exercises_dch.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo # dostÄ™pne kolory: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey, black, white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: PrzeÅ‚Ä…cz na tryb ciemny
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: PrzeÅ‚Ä…cz na tryb jasny
  features:
    - content.code.copy
  toc:
    depth: 3

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
  - mermaid2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra:
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
