site_name: Physics 2024/25 Summer
nav:
  - Home: index.md
  - Mechanics:
    - ðŸŽ“ Lecture Notes:
      - Lecture Notes: Mechanics/Mechanics.html
    - ðŸ¤” Student Projects:
      - Logistic Equation: Mechanics/logistic_equation_bifurcation.md
      - Double Pendulum: Mechanics/double_pendulum_trajectories.md
      - Lorenz Attractor: Mechanics/lorenz_system_and_attractor.md
      - Predator-Prey Model: Mechanics/predator_prey_model.md
      - Duffing Oscillator: Mechanics/duffing_oscillator.md
      - Henon Map: Mechanics/henon_map.md
      - Chua's Circuit: Mechanics/chuas_circuit.md
      - Pendulum with Damping: Mechanics/pendulum_with_damping_and_forcing.md
      - Three Body Problem: Mechanics/three_body_problem.md
  - Experiments & Statistics:
    - ðŸŽ“ Lecture Notes:
      - Statistics 101: Experiments_Statistics/Statistics.html
    - ðŸ¤” Student Projects:
      - Estiamting Pi: Experiments_Statistics/estimation_of_pi.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo # dostÄ™pne kolory: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey, black, white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: PrzeÅ‚Ä…cz na tryb ciemny
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: PrzeÅ‚Ä…cz na tryb jasny
  features:
    - content.code.copy
  toc:
    depth: 4

markdown_extensions:
  - toc
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
  - mermaid2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra:
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
